spring.application.name=bagcontrol

tasf.b2b.data.aeropuertos=classpath:data/c.1inf54.26.1.v1.Aeropuerto.husos.v1.20250818__estudiantes.txt
tasf.b2b.data.vuelos=classpath:data/planes_vuelo.txt

# Datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
