package pe.edu.pucp.inf.bagcontrol.simulacion.dtos;

public enum TipoEvento {
    SIMULACION_INICIADA,
    AEROPUERTO_ACTUALIZADO,
    VUELO_DESPEGA,
    VUELO_ATERRIZA,
    VUELO_CANCELADO,
    PLAN_GENERADO,
    SIMULACION_PAUSADA,
    SIMULACION_EN_PAUSA,
    SIMULACION_REANUDADA,
    VELOCIDAD_CAMBIADA,
    SIMULACION_DETENIDA,
    SIMULACION_FINALIZADA,
    ERROR
}
