package pe.edu.pucp.inf.bagcontrol.simulacion.dtos.eventos;

public enum TipoEvento {
    SIMULACION_INICIADA,
    AEROPUERTO_ACTUALIZADO,
    ALERTA_AEROPUERTO_SATURADO,
    VUELO_DESPEGA,
    VUELO_ATERRIZA,
    VUELO_CANCELADO,
    PLAN_GENERADO,
    SIMULACION_PAUSADA,
    SIMULACION_EN_PAUSA,
    SIMULACION_REANUDADA,
    VELOCIDAD_CAMBIADA,
    CICLO_COLAPSO_EVALUADO,
    COLAPSO_DETECTADO,
    REPLANIFICACION_ENVIO,
    SIMULACION_DETENIDA,
    SIMULACION_FINALIZADA,
    ERROR
}
